spring:
  data:
    redis:
      host: 120.46.159.231
      port: 6379
      username: default
      password: 2046
      database: 62
logging:
  level:
    root: warn
    org.example: debug
  pattern:
    console: '%-5level %C.%M[%line] - %msg%n'